### ISSUE TITLE
Can I use this action on macos?

### ISSUE THREAD

**Issue by tmshft** [Xotabu4/selenoid-github-action#1]
Hi.

This action worked fine on `ubuntu-latest` (GitHub-hosted runners).

But it does not work on `macos-latest`.

Can I use this on macos?

## log

```
## DOWNLOADING CM AND STARTING SELENOID
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
child_process.js:660
    throw err;
    ^

Error: Command failed: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/Users/runner/runners/2.164.0/work/_actions/Xotabu4/selenoid-github-action/v1/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 2,
  signal: null,
```

## workflow yaml

```
...
jobs:
  job1:

    runs-on: macos-latest

    steps:
    - name: install docker
      run: brew install docker;
           brew cask install docker;
           docker --version;
           open /Applications/Docker.app;
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v1
          
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
...
```

**Comment by Xotabu4** [comment]
@shift-morikawa Hello, it think it should be possible. I will check that. Error shows that curl does not accept parameters for some reason.

**Comment by amuthansakthivel** [comment]
I am trying to setup selenoid and appium server in macos and this bug is currently stopping me from starting selenoid in macOS.

**Comment by Xotabu4** [comment]
@amuthansakthivel sorry, currently i have no possibility to code, since russia invaded ukraine and i had to left my house

**Comment by amuthansakthivel** [comment]
Sorry to hear that. Hope peace prevails and Ukraine get back to normalcy.
